services:
  - type: web
    name: macbook-notify-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AUTH_TOKEN
        sync: false
